-- Add all possible retrievable fields to nba_players table
ALTER TABLE nba_players
  ADD COLUMN IF NOT EXISTS external_player_id bigint,
  ADD COLUMN IF NOT EXISTS first_name text,
  ADD COLUMN IF NOT EXISTS last_name text,
  ADD COLUMN IF NOT EXISTS team_id text,
  ADD COLUMN IF NOT EXISTS primary_position text,
  ADD COLUMN IF NOT EXISTS jersey_number text,
  ADD COLUMN IF NOT EXISTS birth_date text,
  ADD COLUMN IF NOT EXISTS birth_city text,
  ADD COLUMN IF NOT EXISTS birth_country text,
  ADD COLUMN IF NOT EXISTS height text,
  ADD COLUMN IF NOT EXISTS weight text,
  ADD COLUMN IF NOT EXISTS college text,
  ADD COLUMN IF NOT EXISTS rookie boolean,
  ADD COLUMN IF NOT EXISTS active boolean,
  ADD COLUMN IF NOT EXISTS photo_url text,
  ADD COLUMN IF NOT EXISTS status text,
  ADD COLUMN IF NOT EXISTS birth_state text,
  ADD COLUMN IF NOT EXISTS experience text,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz;

-- Add all possible retrievable fields to nba_player_season_stats table
ALTER TABLE nba_player_season_stats
  ADD COLUMN IF NOT EXISTS player_id text,
  ADD COLUMN IF NOT EXISTS team_id text,
  ADD COLUMN IF NOT EXISTS season int,
  ADD COLUMN IF NOT EXISTS external_player_id bigint,
  ADD COLUMN IF NOT EXISTS external_team_id text,
  ADD COLUMN IF NOT EXISTS name text,
  ADD COLUMN IF NOT EXISTS team_abbreviation text,
  ADD COLUMN IF NOT EXISTS games_played int,
  ADD COLUMN IF NOT EXISTS minutes_played int,
  ADD COLUMN IF NOT EXISTS field_goals_made int,
  ADD COLUMN IF NOT EXISTS field_goals_attempted int,
  ADD COLUMN IF NOT EXISTS field_goal_percentage float,
  ADD COLUMN IF NOT EXISTS three_pointers_made int,
  ADD COLUMN IF NOT EXISTS three_pointers_attempted int,
  ADD COLUMN IF NOT EXISTS three_pointer_percentage float,
  ADD COLUMN IF NOT EXISTS free_throws_made int,
  ADD COLUMN IF NOT EXISTS free_throws_attempted int,
  ADD COLUMN IF NOT EXISTS free_throw_percentage float,
  ADD COLUMN IF NOT EXISTS offensive_rebounds int,
  ADD COLUMN IF NOT EXISTS defensive_rebounds int,
  ADD COLUMN IF NOT EXISTS rebounds int,
  ADD COLUMN IF NOT EXISTS assists int,
  ADD COLUMN IF NOT EXISTS steals int,
  ADD COLUMN IF NOT EXISTS blocks int,
  ADD COLUMN IF NOT EXISTS turnovers int,
  ADD COLUMN IF NOT EXISTS personal_fouls int,
  ADD COLUMN IF NOT EXISTS points int,
  ADD COLUMN IF NOT EXISTS plus_minus int,
  ADD COLUMN IF NOT EXISTS double_doubles int,
  ADD COLUMN IF NOT EXISTS triple_doubles int,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz;
